### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by yaruchen** [BGI-flexlab/SOAPnuke#20]
Hi,
 when I  make  , I met some problem as:
collect2: error: ld returned 1 exit status
make[2]: *** [SOAPnuke] Error 1
make[1]: *** [CMakeFiles/SOAPnuke.dir/all] Error 2
make: *** [all] Error 2

i install the log4cplus 1.0.3  and add it to my ENV  
how can i resolve this problem ?

**Comment by M201575478** [comment]
Try 6th issue's answer！

**Comment by M201575478** [comment]
Try issue 6's answer!
