### ISSUE TITLE
Parameters "-d" and "-7 1" are in conflict in "filter" command

### ISSUE THREAD

**Issue by Yanpengxu** [BGI-flexlab/SOAPnuke#27]
As mentioned in help message ("filter" command):
-d, --rmdup     : <b> remove PCR duplications
-7, --outType: <i> Add /1, /2 at the end of fastq name, 0:not add, 1:add [default: 0]
When I set "-d" and "-7 1", the parameter "-7 1" does not work.

In FilterProcessor.cpp, the scripts are written as below, maybe sth is wrong when running this loop?
  if (rmdup_)
                    {
                        char tempFile[1024];
                        sprintf(tempFile, "%s/%d.sort.temp", outDir_.c_str(), fileNum);
                        tempOFS.open(tempFile);
                        outputTempData(tempOFS, reads1, reads2, outType_);
                        if(dupRateOnly_){
                            ofstream tempOFS1;
                            char dupTempFile[1024];
                            sprintf(dupTempFile, "%s/%d.dup.temp", outDir_.c_str(), fileNum);
                            tempOFS1.open(dupTempFile);
                            outputDupData(tempOFS1, reads1, reads2,size,outType_);
                        }
                        duplications_.clear();
                    }
Could you double-check this problem? Thanks so much!!

**Comment by youngchan919** [comment]
fixed in 1.6.3
