### ISSUE TITLE
number of filted reads is wrong

### ISSUE THREAD

**Issue by lituan** [BGI-flexlab/SOAPnuke#30]
following is output in Statistics_of_Filtered_Reads.txt

the number of "Read with n rate exceed: (%)"  is wrong, 4450 != 477 + 2079

Item                                    	Total 	Percentage	Counts(fq1)	Percentage	Counts(fq2)	Percentage
Total filtered reads (%)                	6788  	100.00%	3394  	100.00%	3394  	100.00%
Reads with adapter (%)                  	2316  	 34.12%	1155  	 34.03%	1110  	 32.70%
Reads with low quality (%)               	22    	  0.32%	2     	  0.06%	9     	  0.27%
Reads with low mean quality (%)         	0     	  0.00%	0     	  0.00%	0     	  0.00%
Reads with duplications (%)             	0     	  0.00%	0     	  0.00%	0     	  0.00%
Read with n rate exceed: (%)            	4450  	 65.56%	477   	 14.05%	2079  	 61.26%
Read with small insert size: (%)        	0     	  0.00%	0     	  0.00%	0     	  0.00%
Reads with PolyA (%)                    	0     	  0.00%	0     	  0.00%	0     	  0.00%

**Comment by youngchan919** [comment]
4450 <= 477 + 2079
the stats contain the overlapped counts
