### ISSUE TITLE
SOAPnuke make failed

### ISSUE THREAD

**Issue by M201575478** [BGI-flexlab/SOAPnuke#31]
CMakeFiles/SOAPnuke.dir/build.make:230: recipe for target 'CMakeFiles/SOAPnuke.dir/SRNAProcessor.cpp.o' failed
make[2]: *** [CMakeFiles/SOAPnuke.dir/SRNAProcessor.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/SOAPnuke.dir/all' failed
make[1]: *** [CMakeFiles/SOAPnuke.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Error in "make" step.
No error in "cmake" step, but there were no  "SRNAProcessor.cpp.o" file in "CMakeFiles/SOAPnuke.dir" directory,  what should I do? I need your help. TKS

**Comment by M201575478** [comment]
[SOAPnuke.txt](https://github.com/BGI-flexlab/SOAPnuke/files/2243386/SOAPnuke.txt)
If there is error in "make" step, try this binary file, this file can be generated in "make" step, because Github don't support uploading "SOAPnuke" file. So I rename the "SOAPnuke" as "SOAPnuke.txt". If you have download this file, rename this file to its original name-"SOAPnuke". Remember that only steps before "make" step have finished, can you execute this binary file.
如果你在“make”这一步出错了，你可以把这个文件下下来去执行。这个文件就是在“make”这一步产生的，因为github不支持“SOAPnuke”文件格式，所以我重命名为“txt”格式。下载之后，最好还是命名为“SOAPnuke”。然后就可以执行这个文件了！记得“make”之前的步骤是必须的，包括安装库文件和“cmake”步骤。

**Comment by youngchan919** [comment]
Please try SOAPnuke 2.X, which needs less third-party libraries and performs much better.

**Comment by AlsoATraveler** [comment]
请问有2.0版本的构建好的可执行文件吗？

> [SOAPnuke.txt](https://github.com/BGI-flexlab/SOAPnuke/files/2243386/SOAPnuke.txt) If there is error in "make" step, try this binary file, this file can be generated in "make" step, because Github don't support uploading "SOAPnuke" file. So I rename the "SOAPnuke" as "SOAPnuke.txt". If you have download this file, rename this file to its original name-"SOAPnuke". Remember that only steps before "make" step have finished, can you execute this binary file. 如果你在“make”这一步出错了，你可以把这个文件下下来去执行。这个文件就是在“make”这一步产生的，因为github不支持“SOAPnuke”文件格式，所以我重命名为“txt”格式。下载之后，最好还是命名为“SOAPnuke”。然后就可以执行这个文件了！记得“make”之前的步骤是必须的，包括安装库文件和“cmake”步骤。
