### ISSUE TITLE
make error in 2.X

### ISSUE THREAD

**Issue by moveAFs** [BGI-flexlab/SOAPnuke#34]
g++ -std=c++11 -g -O3 -c src/gc.cpp -o obj/gc.o
g++ -std=c++11 -g -O3 -c src/global_variable.cpp -o obj/global_variable.o
g++ -std=c++11 -g -O3 -c src/Main.cpp -o obj/Main.o
g++ -std=c++11 -g -O3 -c src/peprocess.cpp -o obj/peprocess.o
src/peprocess.cpp: In member function ‘void* peProcess::sub_thread(PEthreadOpt)’:
src/peprocess.cpp:1057:45: error: ‘gzbuffer’ was not declared in this scope
   gzbuffer(gz_trim_out1[index],1024*1024*160);
                                             ^
src/peprocess.cpp:1068:46: error: ‘gzbuffer’ was not declared in this scope
   gzbuffer(gz_clean_out1[index],1024*1024*160);
                                              ^
src/peprocess.cpp: In member function ‘void peProcess::process_nonssd()’:
src/peprocess.cpp:1294:45: error: ‘gzbuffer’ was not declared in this scope
   gzbuffer(gz_trim_out1_nonssd,1024*1024*160);
                                             ^
src/peprocess.cpp:1304:46: error: ‘gzbuffer’ was not declared in this scope
   gzbuffer(gz_clean_out1_nonssd,1024*1024*160);
                                              ^
src/peprocess.cpp:1314:27: error: ‘gzbuffer’ was not declared in this scope
   gzbuffer(gzfp1,2048*2048);
                           ^
make: *** [obj/peprocess.o] Error 1

**Comment by youngchan919** [comment]
It may help if you update your zlib library.
