### ISSUE TITLE
Make error in SOAPnuke2.

### ISSUE THREAD

**Issue by SeanZhi** [BGI-flexlab/SOAPnuke#36]
./obj/peprocess.o: In function `peProcess::process_nonssd()':
SOAPnuke/SOAPnuke-SOAPnuke2.0/src/peprocess.cpp:1304: undefined reference to `gzbuffer'
/lustre/liyan/01.software/SOAPnuke/SOAPnuke-SOAPnuke2.0/src/peprocess.cpp:1309: undefined reference to `gzbuffer'
SOAPnuke/SOAPnuke-SOAPnuke2.0/src/peprocess.cpp:1294: undefined reference to `gzbuffer'
SOAPnuke/SOAPnuke-SOAPnuke2.0/src/peprocess.cpp:1298: undefined reference to `gzbuffer'
SOAPnuke/SOAPnuke-SOAPnuke2.0/src/peprocess.cpp:1314: undefined reference to `gzbuffer'
./obj/peprocess.o:SOAPnuke/SOAPnuke-SOAPnuke2.0/src/peprocess.cpp:1317: more undefined references to `gzbuffer' follow

**Comment by youngchan919** [comment]
The version of Zlib in your system is too old, which has no 'gzbuffer' function. Please update it.
