### ISSUE TITLE
SOAPnuke filter error

### ISSUE THREAD

**Issue by dulunar** [BGI-flexlab/SOAPnuke#37]
command：
/home/luna/Desktop/Software/SOAPnuke/SOAPnuke filter -n 0.009 -l 10 -q 0.1 -Q 1 -G 1 -1 SRX247249_1.fastq.gz -2 SRX247249_2.fastq.gz -C SRX247249_S1.fastq.gz -D SRX247249_S2.fastq.gz -T 10 -o . -0 log.SOAPnuke
Error:quality is too low,please check the quality system parameter or fastq file

**Comment by youngchan919** [comment]
It may works if you change the -Q param.
