### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by HuaZou** [BGI-flexlab/SOAPnuke#43]
The details of parameters in this software are missing, so please add them in README.md.

**Comment by youngchan919** [comment]
I think it may be lengthy if these content are all added to README.md, so could you please tell me which parameters confuse you? I can clarify them in -h of the software.

**Comment by HuaZou** [comment]
THX, because i didn't know how to choose the parameters of this software and there was no '-h' paramater in this software (version SOAPnuke-1.5.3). In the other hand, README.md for a software contained the usage of parameters is necessary.

**Comment by youngchan919** [comment]
I would like to recommend SOAPnuke 2.X, which needs less third-party libraries and performs much better. The SOAPnuke-1.5.3 is obsolete.
By the way, for all editions so far, -h info will return if you just run the SOAPnuke program without any param.
