### ISSUE TITLE
Occur Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sjlgg** [BGI-flexlab/SOAPnuke#47]
Hello Mr.
I try to use SOAPnuke2 to have a test, and i install it as below:
```
git clone https://github.com/BGI-flexlab/SOAPnuke.git
cd SOAPnuke
make
```

Then I test it using Ubuntu 18.04.3 LTS 64-bit and 32GB RAM.
```
SOAPnuke filter -1 SRR2061818.fastq -C SRR2061818.fastq.gz -o ./cleandata
```
**However it showed this error:**
`Segmentation fault (core dumped)`

I have already install these library:
```
sudo apt-get install libboost-all-dev
sudo apt-get install openssl
sudo apt-get install zlib1g-dev
```
SRR2061818.fastq:
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR206/008/SRR2061818/SRR2061818.fastq.gz

did i do any wrong thing to this software? I don't know how to do with it.
looking forward to your help..

**Comment by berry08** [comment]
Hi, it seems a bug when input is non-gz format file, we will fix it in next version

**Comment by sjlgg** [comment]
彳亍，那我等您下个版本发布后会关闭这个issue。

**Comment by youngchan919** [comment]
> 彳亍，那我等您下个版本发布后会关闭这个issue。

Sorry. It seems like a misunderstanding occured here.
The commit pushed at the time of replying has already fixed the problem.
Please reply here whether the bug has been fixed in your environment.
THX~

**Comment by sjlgg** [comment]
Thank you! My question has been solved~~
