### ISSUE TITLE
make ERROR

### ISSUE THREAD

**Issue by qymeng1996** [BGI-flexlab/SOAPnuke#57]
Hello,I met the new make error, and how can I solve it, thank you.
"GCC version Passes, 4.8.5 >= 4.7"
"ZLIB version Passes, 1.2.7 >= 1.2.3.5"
Makefile:49: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

**Comment by Mirror361025** [comment]
I had the same issue. You should replace the spaces at line 49 with TAB in Makefile.
