### ISSUE TITLE
"seqType" and "qualSys" can't use

### ISSUE THREAD

**Issue by uso2015** [BGI-flexlab/SOAPnuke#59]
Hi,

       when I  used SOAPnuke-2.1.6, I found that the parameter "seqType" and "qualSys" can't use.

**Comment by berry08** [comment]
> Hi,
> 
> ```
>    when I  used SOAPnuke-2.1.6, I found that the parameter "seqType" and "qualSys" can't use.
> ```

These two parameters belong to uncommonly used parameters, which should be set in config file assigned by -c
