### ISSUE TITLE
-l and -q

### ISSUE THREAD

**Issue by walkoface** [BGI-flexlab/SOAPnuke#60]
Hi,

Can anyone help me to understand more about the parameter used in SOAPnuke?

```
-l / --lowQual = low quality threshold, default value is 5
-q / --qualRate= low quality rate threshold, default value is 0.5
```

I am more familiar with Phred value score, so, can I know which parameter in SOAPnuke is similar to this?
And what is the difference between `-l `and `-q`? 

Much appreciated for the help.

**Comment by youngchan919** [comment]
Hello walkoface,

Sorry for getting back to you late. Setting **lowQual** as 5 means all those quality scores smaller than or equals to 5 will be regarded as **low quality**, and setting **qualRate** as 0.5 means all those reads with greater than or equals to 50% bases of low quality will be regarded as **low quality**. For example, if you use the default setting, a 50-bp read would be filtered out if it contains more than or equals to 25 bases whose quality scores are lower than or equals to 5. 

I hope this answer could solve your problem.
