### ISSUE TITLE
编译失败 

### ISSUE THREAD

**Issue by zarl923014** [BGI-flexlab/SOAPnuke#9]
/home/glad_zarl/Biosoft/soapnuke/SOAPnuke/src/threadpool/detail/locking_ptr.hpp:24:29: 致命错误：boost/utility.hpp：没有那个文件或目录
 #include <boost/utility.hpp>
                             ^
编译中断。
make[2]: *** [CMakeFiles/SOAPnuke.dir/Main.cpp.o] 错误 1
make[1]: *** [CMakeFiles/SOAPnuke.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by youngchan919** [comment]
您好，请先安装boost library。

**Comment by M201575478** [comment]
Try issue 6's answer!
